language: ruby
sudo: required

services:
  - docker

git:
  depth: 5

before_install:
  - export PATH=$PATH:$HOME/.local/bin

install:
  #- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make init

before_script:
  - make update-tests

script:
  # Drupal 8
  - make phpcs
  - make behat
