version: '2'
services:
  web:
    #image: dockerdrop/dockerdrop-nginx:latest
    build: ./docker/nginx/
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
    environment:
      #Make this the same for PHP
      NGINX_DOCROOT: www
      NGINX_SERVER_NAME: localhost
      # Set to the same as the PHP_POST_MAX_SIZE, but use lowercase "m"
      NGINX_MAX_BODY_SIZE: 20m

  php:
    #image: dockerdrop/dockerdrop-php:latest
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      PHP_MEMORY_LIMIT: 256M
      PHP_MAX_EXECUTION_TIME: 120
      # If you set this,make sure you also set it for Nginx
      PHP_POST_MAX_SIZE: 20M
      PHP_UPLOAD_MAX_FILESIZE: 20M
      # used by Drush Alias; if not specified Drush defaults to dev
      PHP_SITE_NAME: dev
      # used by Drush alias; if not specified Drush defaults to localhost:8000
      PHP_HOST_NAME: localhost:8000
      # Make this the same for Nginx
      PHP_DOCROOT: www

  db:
    image: mariadb:10.1.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8002:8025"

  selenium:
    image: selenium/standalone-firefox:2.53.0

#  pma:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: db
#     PMA_USER: drupal
#      PMA_PASSWORD: drupal
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    ports:
#      - "8001:80"

volumes:
  mysql-data:
    driver: local
